name: "publish"

on:
  push:
    branches:
      - "release"

  workflow_dispatch:

jobs:
  build-ghpages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Install app dependencies
        run: npm install
        
      - name: Build the site
        run: npm run build-ghpages
      
      - name: Push to ghpages branch
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    outputs:
      releaseId: ${{ steps.tauri.outputs.releaseId }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Read changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog.md
      
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - uses: Swatinem/rust-cache@v1
          
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      
      - name: Install app dependencies
        run: npm install
      
      - name: Build the app
        id: tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: '${{ steps.changelog.outputs.content }}'
          releaseDraft: true
          prerelease: false
          tauriScript: "npm run"

      #- name: Tag commit
        #uses: rickstaa/action-create-tag@v1
        #with:
          #tag: "v${{ steps.version.outputs.current-version }}"
  generate-update:
    needs: build-tauri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version
        id: version
        uses: martinbeentjes/npm-get-version-action@main
      
      - name: Read changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog.md

      - name: Get assets
        uses: actions/github-script@v6
        env:
          releaseId: ${{ needs.build-tauri.outputs.releaseId }}
          version: ${{ steps.version.outputs.current-version }}
          changelog: ${{ steps.changelog.outputs.content }}
        with:
          script: |
            const { releaseId, version, changelog } = process.env;
            
            let response = await github.rest.repos.listReleaseAssets({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId,
            });

            let assets = response.data;

            if (!assets || assets.length === 0)
            {
              core.setFailed("No assets available in response");
              return;
            }

            let update = {
              "name": version,
              "notes": changelog,
              "pub_date": assets[0].updated_at,
              "platforms": {}
            };

            for (const asset of assets)
            {
              const name = asset.name;
              if ((typeof name !== "string" && !(name instanceof String)) || name.endsWith(".sig"))
              {
                continue;
              }

              const sigName = asset.name + ".sig";
              const sigAsset = assets.find(elem => elem.name == sigName);
              if (!sigAsset)
              {
                continue;
              }
              const sig = await github.request(sigAsset.browser_download_url);

              let platform = {
                signature: sig,
                url: asset.browser_download_url
              };

              // TODO: Support more platforms
              const targz = ".tar.gz";
              if (asset.name.endsWith(targz))
              {
                if (asset.name.endsWith(".AppImage", asset.name.lenth - targz.length))
                {
                  update.platforms["linux-x86_64"] = platform;
                }
                else
                {
                  update.platforms["darwin-intel"] = platform;
                }
              }
              else if (asset.name.endsWith(".msi"))
              {
                update.platforms["windows-x86_64"] = platform;
              }
            }

            core.info(update);