name: "publish"

on:
  push:
    branches:
      - "release"

  workflow_dispatch:

jobs:
  get-changes:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.content }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            changelog.md
      
      - name: Ensure changelog updated
        if: steps.changed-files.outputs.any_changed == "false"
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed("changelog.md has not been updated");
      
      - name: Read changelog
        id: changelog
        uses: juliangruber/read-file-action@v1
        with:
          path: ./changelog.md

  build-ghpages:
    runs-on: ubuntu-latest
    needs: get-changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Install app dependencies
        run: npm install
        
      - name: Build the site
        run: npm run build-ghpages
      
      - name: Push to ghpages branch
        uses: s0/git-publish-subdir-action@v2.5.1
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    needs: get-changes
    outputs:
      releaseId: ${{ steps.tauri.outputs.releaseId }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Node.js setup
        uses: actions/setup-node@v1
        with:
          node-version: 16
      
      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: "./src-tauri"
          
      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      
      - name: Install app dependencies
        run: npm install
      
      - name: Build the app
        id: tauri
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
          releaseName: 'v__VERSION__'
          releaseBody: '${{ needs.get-changes.outputs.changelog }}'
          releaseDraft: true
          prerelease: false
          tauriScript: "npm run"

  publish:
    needs: build-tauri
    runs-on: ubuntu-latest
    steps:
      - name: Publish release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          release_id: ${{ needs.build-tauri.outputs.releaseId }}